<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyPortalBack.Domain\MyPortalBack.Domain.csproj" />
    <ProjectReference Include="..\MyPortalBack.Shared\MyPortalBack.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\Contracts\Requests\" />
    <Folder Include="Common\Behaviors\" />
    <Folder Include="Common\Mapping\" />
    <Folder Include="Common\Interfaces\" />
    <Folder Include="Features\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.2.0" />
  </ItemGroup>

</Project>
